# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-29 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('author', models.EmailField(max_length=254)),
                ('lastEdit', models.DateTimeField(default=123456)),
            ],
        ),
    ]
