# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-29 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_things_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThingNetwork',
            new_name='Thing',
        ),
    ]
