# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-29 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('the_things_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='lastEdit',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
    ]
