# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-30 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_things_list', '0002_auto_20180829_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='random_str',
            field=models.CharField(default=12345678901234351, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
